# Generated by Django 2.2.3 on 2019-07-12 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='street2',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
