# Generated by Django 2.2.4 on 2019-08-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20190809_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created'),
        ),
        migrations.AddField(
            model_name='email',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created'),
        ),
        migrations.AddField(
            model_name='phone',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created'),
        ),
    ]
