# Generated by Django 2.2.4 on 2019-08-12 22:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20190812_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='address_id',
            field=models.ManyToManyField(blank=True, related_name='address_contact', to='portfolio.Address'),
        ),
        migrations.AddField(
            model_name='contact',
            name='email_id',
            field=models.ManyToManyField(blank=True, related_name='email_contact', to='portfolio.Email'),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_id',
            field=models.ManyToManyField(blank=True, related_name='phone_contact', to='portfolio.Phone'),
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created Date')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date Updated')),
                ('name', models.CharField(max_length=50, verbose_name='Place Name')),
                ('type', models.CharField(max_length=50, verbose_name='Place Type')),
                ('address_id', models.ManyToManyField(blank=True, related_name='address_place', to='portfolio.Address')),
                ('email_id', models.ManyToManyField(blank=True, related_name='email_place', to='portfolio.Email')),
                ('phone_id', models.ManyToManyField(blank=True, related_name='phone_place', to='portfolio.Phone')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
